version: '2.1'
services:
  db:
    image: mysql:5.7
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: be_db
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    networks:
        - appnet

  web:
    image: nginx:1.12
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/logs/nginx/:/var/log/nginx:cached
    volumes_from:
      - php
    ports:
      - 8080:80
    links:
      - php
    networks:
        - appnet

  php:
    build: ./docker/php-fpm
    ports:
      - 9002:9000
    volumes:
      - ./be:/var/www/be:cached
      - ./docker/logs/be:/var/www/be/var/logs:cached
    networks:
        - appnet
    links:
      - db

networks:
    appnet:
        driver: "bridge"