version: '2.1'
services:
  db:
    image: mysql:5.7
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: be_db
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    networks:
        - appnet

  web:
    image: nginx:1.12
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/logs/nginx/:/var/log/nginx:cached
    volumes_from:
      - php
    ports:
      - 8080:80
    links:
      - php
    networks:
        - appnet

  php:
    build: ./docker/php-fpm
    ports:
      - 9002:9000
    volumes:
      - ./be:/var/www/be:cached
      - ./docker/logs/be:/var/www/be/var/logs:cached
    networks:
        - appnet
    links:
      - db
#  elastic:
#    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
#    environment:
#      - cluster.name=docker-cluster
#     # - bootstrap.memory_lock=true
#     # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#      - "http.host=0.0.0.0"
#      - "transport.host=127.0.0.1"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    volumes:
#      - ./docker/elastic/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
#    #  - esdata1:/usr/share/elasticsearch/data
#    ports:
#      - 9200:9200
#    networks:
#      - appnet

networks:
    appnet:
        driver: "bridge"